create table stock_trade_daily_statics (
                                           id bigint not null,
                                           trade_date timestamp(6) not null,
                                           stock_code integer not null,
                                           stock_name varchar(255) not null,
                                           pre_day_closing_price Decimal(14,0) default '0',
                                           current_price Decimal(14,0) default '0',
                                           trade_volume Decimal(14,0) default '0',
                                           view_count integer default 0,
                                           created_at timestamp(6),
                                           updated_at timestamp(6),
                                           primary key (id)
);

create index trade_date_idx
    on stock_trade_daily_statics (trade_date);
--샘플데이터 생성
Insert into stock_trade_daily_statics(id,stock_code, stock_name, pre_day_closing_price,trade_date)  values
                                                                                                  (1,5930,'삼성전자',61500,CURRENT_DATE )
                                                                                                 ,(2,373220,'LG에너지솔루션',452000,CURRENT_DATE )
                                                                                                 ,(3,660,'SK하이닉스',95700,CURRENT_DATE )
                                                                                                 ,(4,207940,'삼성바이오로직스',875000,CURRENT_DATE )
                                                                                                 ,(5,5935,'삼성전자우',56400,CURRENT_DATE )
                                                                                                 ,(6,51910,'LG화학',651000,CURRENT_DATE )
                                                                                                 ,(7,6400,'삼성SDI',624000,CURRENT_DATE )
                                                                                                 ,(8,35420,'NAVER',250000,CURRENT_DATE )
                                                                                                 ,(9,5380,'현대차',186000,CURRENT_DATE )
                                                                                                 ,(10,35720,'카카오',79200,CURRENT_DATE )
                                                                                                 ,(11,270,'기아',76700,CURRENT_DATE )
                                                                                                 ,(12,68270,'셀트리온',202500,CURRENT_DATE )
                                                                                                 ,(13,28260,'삼성물산',120500,CURRENT_DATE )
                                                                                                 ,(14,5490,'POSCO홀딩스',256000,CURRENT_DATE )
                                                                                                 ,(15,105560,'KB금융',50700,CURRENT_DATE )
                                                                                                 ,(16,12330,'현대모비스',211000,CURRENT_DATE )
                                                                                                 ,(17,96770,'SK이노베이션',210500,CURRENT_DATE )
                                                                                                 ,(18,55550,'신한지주',35500,CURRENT_DATE )
                                                                                                 ,(19,34730,'SK',236000,CURRENT_DATE )
                                                                                                 ,(20,66570,'LG전자',102000,CURRENT_DATE )
                                                                                                 ,(21,323410,'카카오뱅크',31200,CURRENT_DATE )
                                                                                                 ,(22,15760,'한국전력',21550,CURRENT_DATE )
                                                                                                 ,(23,34020,'두산에너빌리티',21450,CURRENT_DATE )
                                                                                                 ,(24,3550,'LG',84300,CURRENT_DATE )
                                                                                                 ,(25,259960,'크래프톤',258000,CURRENT_DATE )
                                                                                                 ,(26,3670,'포스코케미칼',161500,CURRENT_DATE )
                                                                                                 ,(27,32830,'삼성생명',62000,CURRENT_DATE )
                                                                                                 ,(28,329180,'현대중공업',134500,CURRENT_DATE )
                                                                                                 ,(29,11200,'HMM',23550,CURRENT_DATE )
                                                                                                 ,(30,86790,'하나금융지주',38500,CURRENT_DATE )
                                                                                                 ,(31,51900,'LG생활건강',726000,CURRENT_DATE )
                                                                                                 ,(32,17670,'SK텔레콤',51200,CURRENT_DATE )
                                                                                                 ,(33,33780,'KT&G',81200,CURRENT_DATE )
                                                                                                 ,(34,10130,'고려아연',589000,CURRENT_DATE )
                                                                                                 ,(35,10950,'S-Oil',92300,CURRENT_DATE )
                                                                                                 ,(36,9150,'삼성전기',138000,CURRENT_DATE )
                                                                                                 ,(37,18260,'삼성에스디에스',133000,CURRENT_DATE )
                                                                                                 ,(38,30200,'KT',38000,CURRENT_DATE )
                                                                                                 ,(39,3490,'대한항공',26500,CURRENT_DATE )
                                                                                                 ,(40,810,'삼성화재',198500,CURRENT_DATE )
                                                                                                 ,(41,302440,'SK바이오사이언스',122000,CURRENT_DATE )
                                                                                                 ,(42,377300,'카카오페이',68400,CURRENT_DATE )
                                                                                                 ,(43,9830,'한화솔루션',46600,CURRENT_DATE )
                                                                                                 ,(44,316140,'우리금융지주',12200,CURRENT_DATE )
                                                                                                 ,(45,36570,'엔씨소프트',382500,CURRENT_DATE )
                                                                                                 ,(46,11070,'LG이노텍',347000,CURRENT_DATE )
                                                                                                 ,(47,352820,'하이브',188000,CURRENT_DATE )
                                                                                                 ,(48,90430,'아모레퍼시픽',128000,CURRENT_DATE )
                                                                                                 ,(49,24110,'기업은행',9690,CURRENT_DATE )
                                                                                                 ,(50,361610,'SK아이이테크놀로지',94700,CURRENT_DATE )
                                                                                                 ,(51,86280,'현대글로비스',178500,CURRENT_DATE )
                                                                                                 ,(52,9540,'한국조선해양',92100,CURRENT_DATE )
                                                                                                 ,(53,97950,'CJ제일제당',419000,CURRENT_DATE )
                                                                                                 ,(54,11170,'롯데케미칼',182000,CURRENT_DATE )
                                                                                                 ,(55,402340,'SK스퀘어',43600,CURRENT_DATE )
                                                                                                 ,(56,326030,'SK바이오팜',78000,CURRENT_DATE )
                                                                                                 ,(57,34220,'LG디스플레이',16250,CURRENT_DATE )
                                                                                                 ,(58,251270,'넷마블',67300,CURRENT_DATE )
                                                                                                 ,(59,383220,'F&F',149000,CURRENT_DATE )
                                                                                                 ,(60,18880,'한온시스템',10600,CURRENT_DATE )
                                                                                                 ,(61,35250,'강원랜드',26400,CURRENT_DATE )
                                                                                                 ,(62,47810,'한국항공우주',56100,CURRENT_DATE )
                                                                                                 ,(63,69500,'KODEX 200',32915,CURRENT_DATE )
                                                                                                 ,(64,32640,'LG유플러스',12350,CURRENT_DATE )
                                                                                                 ,(65,10140,'삼성중공업',5990,CURRENT_DATE )
                                                                                                 ,(66,88980,'맥쿼리인프라',12850,CURRENT_DATE )
                                                                                                 ,(67,720,'현대건설',46400,CURRENT_DATE )
                                                                                                 ,(68,11790,'SKC',132500,CURRENT_DATE )
                                                                                                 ,(69,161390,'한국타이어앤테크놀로지',38950,CURRENT_DATE )
                                                                                                 ,(70,21240,'코웨이',65000,CURRENT_DATE )
                                                                                                 ,(71,267250,'HD현대',59400,CURRENT_DATE )
                                                                                                 ,(72,60,'메리츠화재',38150,CURRENT_DATE )
                                                                                                 ,(73,4020,'현대제철',33250,CURRENT_DATE )
                                                                                                 ,(74,5830,'DB손해보험',62400,CURRENT_DATE )
                                                                                                 ,(75,28050,'삼성엔지니어링',22400,CURRENT_DATE )
                                                                                                 ,(76,10620,'현대미포조선',108000,CURRENT_DATE )
                                                                                                 ,(77,271560,'오리온',109000,CURRENT_DATE )
                                                                                                 ,(78,100,'유한양행',56800,CURRENT_DATE )
                                                                                                 ,(79,6800,'미래에셋증권',6730,CURRENT_DATE )
                                                                                                 ,(80,180640,'한진칼',61800,CURRENT_DATE )
                                                                                                 ,(81,78930,'GS',44200,CURRENT_DATE )
                                                                                                 ,(82,4990,'롯데지주',38900,CURRENT_DATE )
                                                                                                 ,(83,11780,'금호석유',131500,CURRENT_DATE )
                                                                                                 ,(84,138040,'메리츠금융지주',30050,CURRENT_DATE )
                                                                                                 ,(85,137310,'에스디바이오센서',37350,CURRENT_DATE )
                                                                                                 ,(86,36460,'한국가스공사',41700,CURRENT_DATE )
                                                                                                 ,(87,128940,'한미약품',311500,CURRENT_DATE )
                                                                                                 ,(88,371460,'TIGER 차이나전기차SOLACTIVE',16600,CURRENT_DATE )
                                                                                                 ,(89,29780,'삼성카드',31550,CURRENT_DATE )
                                                                                                 ,(90,12450,'한화에어로스페이스',71400,CURRENT_DATE )
                                                                                                 ,(91,3410,'쌍용C&E',7030,CURRENT_DATE )
                                                                                                 ,(92,71050,'한국금융지주',61200,CURRENT_DATE )
                                                                                                 ,(93,20150,'일진머티리얼즈',72500,CURRENT_DATE )
                                                                                                 ,(94,5940,'NH투자증권',10050,CURRENT_DATE )
                                                                                                 ,(95,241560,'두산밥캣',33200,CURRENT_DATE )
                                                                                                 ,(96,307950,'현대오토에버',120500,CURRENT_DATE )
                                                                                                 ,(97,5387,'현대차2우B',89800,CURRENT_DATE )
                                                                                                 ,(98,8560,'메리츠증권',4930,CURRENT_DATE )
                                                                                                 ,(99,16360,'삼성증권',35100,CURRENT_DATE )
                                                                                                 ,(100,47050,'포스코인터내셔널',25150,CURRENT_DATE )
                                                                                                 ,(101,1450,'현대해상',34100,CURRENT_DATE )
                                                                                                 ,(102,282330,'BGF리테일',174500,CURRENT_DATE )
                                                                                                 ,(103,10060,'OCI',124000,CURRENT_DATE )
                                                                                                 ,(104,28670,'팬오션',5520,CURRENT_DATE )
                                                                                                 ,(105,2790,'아모레G',35600,CURRENT_DATE )
                                                                                                 ,(106,139480,'이마트',105000,CURRENT_DATE )
                                                                                                 ,(107,272210,'한화시스템',15300,CURRENT_DATE )
                                                                                                 ,(108,120,'CJ대한통운',126500,CURRENT_DATE )
                                                                                                 ,(109,23530,'롯데쇼핑',101500,CURRENT_DATE )
                                                                                                 ,(110,52690,'한전기술',74900,CURRENT_DATE )
                                                                                                 ,(111,8930,'한미사이언스',41600,CURRENT_DATE )
                                                                                                 ,(112,8770,'호텔신라',72200,CURRENT_DATE )
                                                                                                 ,(113,64350,'현대로템',25750,CURRENT_DATE )
                                                                                                 ,(114,112610,'씨에스윈드',64900,CURRENT_DATE )
                                                                                                 ,(115,2380,'KCC',306000,CURRENT_DATE )
                                                                                                 ,(116,6360,'GS건설',31500,CURRENT_DATE )
                                                                                                 ,(117,7070,'GS리테일',25600,CURRENT_DATE )
                                                                                                 ,(118,14680,'한솔케미칼',230500,CURRENT_DATE )
                                                                                                 ,(119,30000,'제일기획',22350,CURRENT_DATE )
                                                                                                 ,(120,26960,'동서',25650,CURRENT_DATE );

--샘플데이터 현재가 전일종가로 초기화
update stock_trade_daily_statics
set current_price = pre_day_closing_price
WHERE trade_date = CURRENT_DATE;